### ISSUE TITLE
Bower recommendations

### ISSUE THREAD

**Issue by leolux** [baldurpan/jquery-parallax#1]
1. Add version tags to your github repo like 1.0.0 (http://semver.org/)
2. Change "main" value in bower.json to the non-minified version (minification is the responsibility of a build tool in a real project). This allows for better debugging during development

http://bower.io/docs/creating-packages/#register

**Comment by leolux** [comment]
That was fast :-) Thank you!

**Comment by baldurpan** [comment]
No problem mate. :)
